name: Build and Deploy Docs

on:
  push:
    branches: [ main ]  # Run whenever you push to main

permissions:
  contents: write  # Required for pushing to gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Get your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Python environment
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # <-- [CHECK THIS] Specs the version you use locally

      # Step 3: Install project and docs dependencies
      - name: Install dependencies
        # V [CHECK THIS] use the appropriate package manager
        run: |
          python -m pip install --upgrade pip 
          pip install .[docs]

      # Step 4: Build Sphinx docs
      - name: Build HTML
        # V [CHECK THIS] this command may change depending on the package manager
        run: |
          sphinx-build -b html docs/source docs/_build/html

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          # destination_dir: docs  # <-- [CHECK THIS] Uncomment this to deploy to a {website}/docs